[project]
name = "generate-your-own-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.19"
dependencies = [
    "keras>=3.12.0",
    "music21>=9.9.1",
    "pygame>=2.6.1",
    "tensorflow>=2.20.0",
]
